global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'spring-boot-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['172.168.20.53:8070']

