version: "3.8"
services:
  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
#    restart: always



#        version: "3.9"
#
#        services:
#          nextapp:
#            container_name: hello-next
#            build: .
#            ports:
#              - "3000:3000"
#            environment:
#              - NODE_ENV=production
#            restart: always